/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package exercise5;

import GUI.GenericRadarPanel;
import GUI.RadarPanelInt;
import GUI.TrafficGraphic;
import GUI.TrafficPlot;
import antenna.AntennaReceiver;
import traffic.Traffic;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.geom.Rectangle2D;
import traffic.TrafficListener;


/**
 *
 * @author jvila
 */
public class RadarPanel extends GenericRadarPanel implements TrafficListener {

    // Area of interest:Valencia
    
    private final Double lonWest  = -4.0; 
    private final Double lonEast  =  4.0;
    private final Double latNorth =  42.0;
    private final Double latSouth =  37.0;

    // size
    double sizeEW = lonEast - lonWest;
    double sizeNS = latNorth - latSouth;
    
    private Rectangle2D  mapArea;
    
    // Traffic source
    AntennaReceiver ar;
    
    private Timeout tout;
    
    
    public RadarPanel(AntennaReceiver ar) {
        initComponents();
        this.ar=ar;
        mapArea = new Rectangle2D.Double(lonWest, latNorth, lonEast-lonWest, latNorth-latSouth);
        
        tout=new Timeout(2000);
        tout.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    }
    
    @Override
    public Rectangle2D getArea() {
        return mapArea;
    }
                
    
    private synchronized void removeTraffics() {
        Component[] componentList = this.getComponents();
        for (Component c : componentList) {
            if (c instanceof TrafficPlot) {
                remove(c);
            }
        }
        //IMPORTANT
        this.revalidate();
    }

    @Override
    public void putTraffic(Traffic t) {     
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        
        if (tg == null) {
            tg = new TrafficGraphic(t, this);
            //t.setTrafficExt(tg);
            this.add(tg.getTrafficPlot());
            System.out.println("added: "+t.getCallsign());
        }

        tout.activity();
        revalidate();
        repaint();
    }

    @Override
    public void removeTraffic(Traffic t) {
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        this.remove(tg.getTrafficPlot());
        tout.activity();
        revalidate();
        repaint();
    }

    @Override
    public void updateTraffic(Traffic t) {
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        
        if (tg == null) {
            tg = new TrafficGraphic(t, this);
            //t.setTrafficExt(tg);
            this.add(tg.getTrafficPlot());         
        }
        System.out.println("updated: "+t.getCallsign());
        
        tout.activity();
        repaint();
    }

    @Override
    public void stop() {
        this.removeTraffics();
        revalidate();
        repaint();
    }

    
    //--------------------------------------------------------------------------
    class Timeout extends Thread {

        private boolean activity;
        private int period;

        public Timeout(int period) {
            this.period = period;
            activity = false;
        }

        public void activity() {
            activity = true;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(period);
                } catch (InterruptedException ex) {
                }
                if (!activity) {
                    removeTraffics();
                    //refreshTraffics();
                    repaint();
                }
                activity = false;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
