/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise5;

import antenna.AntennaReceiver;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Iterator;
import traffic.Traffic;

/**
 *
 * @author jvila
 */


public class RadarPanel1 extends javax.swing.JPanel {

    // Area of interest: Valencia
    private final Double lonWest  = -4.0; 
    private final Double lonEast  = 4.0;
    private final Double latNorth = 42.0;
    private final Double latSouth = 37.0;

    // size 
    double sizeEW = lonEast - lonWest;
    double sizeNS = latNorth - latSouth;

    TrafficSelector parent;
    AntennaReceiver ar;
    Traffic st;
    Graphics2D g2;
    
    
    /**
     * Creates new form CPaint
     */
    public RadarPanel1(TrafficSelector ts, AntennaReceiver ar) {
        this.parent=ts;
        this.ar=ar;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    public void setTraffic(Traffic st){
//        this.st=st;
//    }
    
    private void paintTraffic(Graphics2D g2,Traffic st) {

        //System.out.println("Traffic "+st.getICAO24()+" ("+st.getLongitude()+", "+st.getLatitude()+")");
             
        int yCoord = (int) (getHeight() * (latNorth - st.getLatitude()) / sizeNS);
        int xCoord = (int) (getWidth() * (st.getLongitude() - lonWest) / sizeEW);

        g2.setColor(Color.WHITE);
        g2.fillRect(xCoord - 2, yCoord - 2, 5, 5);
        g2.drawLine(xCoord, yCoord, xCoord + 5, yCoord - 5);
        g2.drawString(st.getICAO24(), xCoord + 5, yCoord - 5);
    }
    
    private void paintAllTraffics(Graphics2D g2) {
        java.util.Map<String, Traffic> traffics=null;        
        Traffic tr;
        String key;
        
        if (ar != null) {
            traffics = ar.getTrafficMap();
        } else {
            traffics = null;
        }

        if (traffics != null) {
            Iterator it = traffics.keySet().iterator();
            while (it.hasNext()) {
                key = (String) it.next();
                tr = (Traffic) traffics.get(key);
                paintTraffic(g2,tr);   
            }
        }  
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g2 = (Graphics2D) g;
        System.out.println("Repainting radar panel ");

//        st=parent.getSelectedTraffic();
//        if (st!=null){
//            paintTraffic(g2,st); 
//        }

        paintAllTraffics(g2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
