/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package exercise6;

import GUI.Map;
import GUI.GenericRadarPanel;
import GUI.Polygon;
import GUI.PolygonArrayPlot;
import GUI.TrafficGraphic;
import GUI.TrafficPlot;
import antenna.AntennaReceiver;
import java.awt.Color;
import traffic.Traffic;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Path2D;
import java.awt.geom.Rectangle2D;
import java.io.IOException;
import traffic.TrafficListener;


/**
 *
 * @author jvila
 */
public class RadarPanel extends GenericRadarPanel implements TrafficListener {

    // Area of interest:  Valencia
    private final Double lonWest  = -1.78; 
    private final Double lonEast  = 1.22;
    private final Double latNorth = 40.79;
    private final Double latSouth = 37.79;
    // size
    double sizeEW = lonEast - lonWest;
    double sizeNS = latNorth - latSouth;
    
    private Dimension preferredSize;
    
    // Map definition
    private String mapfile;
    private Map map;
    private Polygon[] map_p;
    private Component map_c;
    
    private Rectangle2D  mapArea;
    
    // Traffic source
    AntennaReceiver ar;
    
    private Timeout tout;
    
    
    public RadarPanel(String mapfile, AntennaReceiver ar) {
        initComponents();
        this.ar=ar;
        
        mapArea = new Rectangle2D.Double(lonWest, latNorth, lonEast-lonWest, latNorth-latSouth);
        
        preferredSize=new Dimension(750,900);
        this.setPreferredSize(preferredSize);
        this.setBounds(0, 0, 750, 900);
        
        ar.setListener(this);
        
        try {
            map= new Map(mapfile, Color.GREEN);
        } catch (IOException ex) {
            System.out.println("RadarPanel: file "+mapfile+" not found.");
        }
     
        this.map_p = this.map.getMap();
        
        if (this.map != null) {
            map_c = new PolygonArrayPlot(this.map_p, map.getColor(), this);
            this.add(map_c);
        } 
        
        this.setVisible(true);
        
        tout=new Timeout(2000);
        tout.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Dimension getPreferredSize() {
        //return super.getPreferredSize(); //To change body of generated methods, choose Tools | Templates.
        return this.preferredSize;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    }
    
    @Override
    public Rectangle2D getArea() {
        return mapArea;
    }
                
    
    private synchronized void removeTraffics() {
        Component[] componentList = this.getComponents();
        for (Component c : componentList) {
            if (c instanceof TrafficPlot) {
                remove(c);
            }
        }
        //IMPORTANT
        this.revalidate();
    }

    @Override
    public void putTraffic(Traffic t) {     
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        
        if (tg == null) {
            tg = new TrafficGraphic(t, this);
            //t.setTrafficExt(tg);
            this.add(tg.getTrafficPlot());
            System.out.println("added: "+t.getCallsign());
        }

        tout.activity();
        revalidate();
        repaint();
    }

    @Override
    public void removeTraffic(Traffic t) {
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        this.remove(tg.getTrafficPlot());
        tout.activity();
        revalidate();
        repaint();
    }

    @Override
    public void updateTraffic(Traffic t) {
        TrafficGraphic tg = (TrafficGraphic) t.getTrafficExt();
        
        if (tg == null) {
            tg = new TrafficGraphic(t, this);
            //t.setTrafficExt(tg);
            this.add(tg.getTrafficPlot());         
        }
        System.out.println("updated: "+t.getCallsign());
        
        java.util.List<TrafficGraphic> allTraffic = getAllTrafficGraphics();
        GUI.ConflictManager.updateConflicts(allTraffic);
        
        tout.activity();
        repaint();
    }

    @Override
    public void stop() {
        this.removeTraffics();
        revalidate();
        repaint();
    }
    
    private java.util.List<TrafficGraphic> getAllTrafficGraphics() {
        java.util.List<TrafficGraphic> list = new java.util.ArrayList<>();
        for (java.awt.Component c : this.getComponents()) {
            if (c instanceof TrafficPlot) {
                list.add(((TrafficPlot) c).getTrafficGraphic());
            }
        }
        return list;
    }
    
    //--------------------------------------------------------------------------
    class Timeout extends Thread {

        private boolean activity;
        private int period;

        public Timeout(int period) {
            this.period = period;
            activity = false;
        }

        public void activity() {
            activity = true;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(period);
                } catch (InterruptedException ex) {
                }
                if (!activity) {
                    removeTraffics();
                    //refreshTraffics();
                    repaint();
                }
                activity = false;
            }
        }
    }
    
    
//    public void paintMap(Graphics2D g) {
//        Graphics2D g2 = (Graphics2D) g;
//
//        Path2D path = new Path2D.Double(Path2D.WIND_EVEN_ODD);
//        for (int i = 0; i < map.data.length; i++) {
//            int lonNor = (int) (this.getWidth() * (map.data[i].point[0].longitude - mapArea.getX()) / mapArea.getWidth()); // normalization
//            int latNor = (int) (this.getHeight() * (mapArea.getY() - map.data[i].point[0].latitude) / mapArea.getHeight());
//            path.moveTo(lonNor, latNor);
//            for (int j = 1; j < map.data[i].point.length; j++) {
//                //   System.out.println(map.data[i].data[j].latitude + " " + map.data[i].data[j].longitude);
//
//                lonNor = (int) (this.getWidth() * (map.data[i].point[j].longitude - mapArea.getX()) / mapArea.getWidth()); // normalization
//                latNor = (int) (this.getHeight() * (mapArea.getY() - map.data[i].point[j].latitude) / mapArea.getHeight());
//                path.lineTo(lonNor, latNor);
//
//            }
//
//            //System.out.println(i + " ********************************************");
//        }
//        path.closePath();
//        g2.setColor(Color.yellow);
//        g2.draw(path);
//
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
//holagi