/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise2;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.TexturePaint;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.CubicCurve2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import java.awt.geom.QuadCurve2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fms
 */
public class CanvasFrame extends javax.swing.JFrame {

    /**
     * Creates new form CanvasFrame
     */
    Aoi aoi;

    public CanvasFrame() {
        initComponents();
        aoi = new Aoi(canvasPanel, canvasPanel.getWidth() / 2, canvasPanel.getHeight() / 2, canvasPanel.getHeight() / 4, Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvasPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        quadButton = new javax.swing.JButton();
        linesButton1 = new javax.swing.JButton();
        cubicButton = new javax.swing.JButton();
        rectButton = new javax.swing.JButton();
        rectRoundButton = new javax.swing.JButton();
        arcButton = new javax.swing.JButton();
        pathButton = new javax.swing.JButton();
        opsButton = new javax.swing.JButton();
        fillButton = new javax.swing.JButton();
        ellipseButton = new javax.swing.JButton();
        contourButton = new javax.swing.JButton();
        translateButton = new javax.swing.JButton();
        rotateButton = new javax.swing.JButton();
        scaleButton = new javax.swing.JButton();
        shearButton = new javax.swing.JButton();
        clipButton = new javax.swing.JButton();
        textButton = new javax.swing.JButton();
        rotateTextButton = new javax.swing.JButton();
        clrButton = new javax.swing.JButton();
        aoiButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvasPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        canvasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        quadButton.setText("quad");
        quadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quadButtonActionPerformed(evt);
            }
        });

        linesButton1.setText("lines");
        linesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linesButton1ActionPerformed(evt);
            }
        });

        cubicButton.setText("cubic");
        cubicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubicButtonActionPerformed(evt);
            }
        });

        rectButton.setText("rect");
        rectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectButtonActionPerformed(evt);
            }
        });

        rectRoundButton.setText("rectR");
        rectRoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectRoundButtonActionPerformed(evt);
            }
        });

        arcButton.setText("arc");
        arcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcButtonActionPerformed(evt);
            }
        });

        pathButton.setText("path");
        pathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathButtonActionPerformed(evt);
            }
        });

        opsButton.setText("ops");
        opsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsButtonActionPerformed(evt);
            }
        });

        fillButton.setText("fill");
        fillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillButtonActionPerformed(evt);
            }
        });

        ellipseButton.setText("ellipse");
        ellipseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellipseButtonActionPerformed(evt);
            }
        });

        contourButton.setText("contour");
        contourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contourButtonActionPerformed(evt);
            }
        });

        translateButton.setText("translate");
        translateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateButtonActionPerformed(evt);
            }
        });

        rotateButton.setText("rotate");
        rotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateButtonActionPerformed(evt);
            }
        });

        scaleButton.setText("scale");
        scaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleButtonActionPerformed(evt);
            }
        });

        shearButton.setText("deform");
        shearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shearButtonActionPerformed(evt);
            }
        });

        clipButton.setText("clip");
        clipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clipButtonActionPerformed(evt);
            }
        });

        textButton.setText("text");
        textButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtonActionPerformed(evt);
            }
        });

        rotateTextButton.setText("rot. text");
        rotateTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateTextButtonActionPerformed(evt);
            }
        });

        clrButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clrButton.setText("clr");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        aoiButton.setText("Aoi");
        aoiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aoiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(clrButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(linesButton1)
                        .addGap(6, 6, 6)
                        .addComponent(quadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cubicButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rectRoundButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ellipseButton)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(arcButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(translateButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rotateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scaleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clipButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotateTextButton)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linesButton1)
                            .addComponent(quadButton)
                            .addComponent(cubicButton)
                            .addComponent(rectButton)
                            .addComponent(rectRoundButton)
                            .addComponent(ellipseButton))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arcButton)
                            .addComponent(pathButton)
                            .addComponent(opsButton)
                            .addComponent(fillButton)
                            .addComponent(contourButton)
                            .addComponent(translateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotateButton)
                            .addComponent(scaleButton)
                            .addComponent(shearButton)
                            .addComponent(clipButton)
                            .addComponent(textButton)
                            .addComponent(rotateTextButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(clrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aoiButton)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quadButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        QuadCurve2D q = new QuadCurve2D.Double();
        Color[] colores = {Color.red, Color.green, Color.blue};
        int numeroCurvas = 7;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        Point2D pi = new Point2D.Double(50, d.height / 2);
        Point2D pf = new Point2D.Double(d.width - 50, d.height / 2);
        Point2D pc;
        for (int i = 0; i < numeroCurvas; i++) {
            double radio = (double) i / numeroCurvas;
            double iradio = 1 - radio;
            // Dibuja el punto de control externo de la curva
            pc = new Point2D.Double(50 + (d.width - 100) * radio,
                    (d.height - 100) * iradio);
            dibujaPunto(canvasPanel, pc, colores[i % colores.length]);
            // Establece el color de la curva
            g2.setPaint(colores[i % colores.length]);
            // Dibuja la curva cuadrática
            q.setCurve(pi, pc, pf);
            g2.draw(q);
        }


    }//GEN-LAST:event_quadButtonActionPerformed

    public static void dibujaPunto(JPanel lienzo, Point2D p, Paint paint) {
        Graphics g = lienzo.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Establece el color del punto
        g2.setPaint(paint);
        // Dibuja el punto como un circulo de radio 5
        Ellipse2D e = new Ellipse2D.Double(p.getX(), p.getY(), 5, 5);
        g2.fill(e);
    }

    private void linesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linesButton1ActionPerformed
        // Obtiene un objeto de tipo Graphics2D del panelLienzo
        Graphics2D g2 = (Graphics2D) canvasPanel.getGraphics();
        int numeroLineas = 25;
        Color[] colores = {Color.red, Color.green, Color.blue};
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        for (int i = 0; i < numeroLineas; i++) {
            // Establece el color de la linea
            g2.setPaint(colores[i % colores.length]);
            double radio = (double) i / numeroLineas;
            double iradio = 1 - radio;
            // Dibuja una linea en la esquina inferior izquierda
            Line2D linea1 = new Line2D.Double(0, radio * d.height, radio * d.width, d.height);
            g2.draw(linea1);
            // Dibuja una linea en la esquina superior derecha
            Line2D linea2 = new Line2D.Double(d.width, iradio * d.height, iradio * d.width, 0);
            g2.draw(linea2);
        }
    }//GEN-LAST:event_linesButton1ActionPerformed

    private void cubicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubicButtonActionPerformed

        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        CubicCurve2D q = new CubicCurve2D.Double();
        Color[] colores1 = {Color.red, Color.green, Color.blue};
        int numeroCurvas = 5;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        Point2D pi = new Point2D.Double(50, d.height / 2);
        Point2D pf = new Point2D.Double(d.width - 50, d.height / 2);
        Point2D pc1, pc2;
        for (int i = 0; i < numeroCurvas; i++) {
            double radio = (double) i / numeroCurvas;
            double iradio = 1 - radio;
            // Dibuja el punto de control 1 externo de la curva
            pc1 = new Point2D.Double(50 + (d.width - 100) * radio / 2,
                    (d.height - 100) * iradio);
            dibujaPunto(canvasPanel, pc1, colores1[i % colores1.length]);
            // Dibuja el punto de control 2 externo de la curva
            pc2 = new Point2D.Double(d.width * (1 + radio) / 2,
                    50 + (d.height - 100) * radio);
            dibujaPunto(canvasPanel, pc2, colores1[i % colores1.length]);
            // Establece el color de la curva
            g2.setPaint(colores1[i % colores1.length]);
            // Dibuja la curva cubica
            q.setCurve(pi, pc1, pc2, pf);
            g2.draw(q);
        }


    }//GEN-LAST:event_cubicButtonActionPerformed

    private void rectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        int numeroRectangulos = 5;
        Color[] colores = {Color.red, Color.green, Color.blue};
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double x = 0;
        for (int i = 0; i < numeroRectangulos; i++) {
            // Establece el color de la rectangulo
            g2.setPaint(colores[i % colores.length]);
            double paso = d.width / numeroRectangulos;
            double alto = paso / (i + 1);
            // Dibuja un rectangulo en superior
            Rectangle2D rectangulo1 = new Rectangle2D.Double(i * paso, 0, paso, alto);
            g2.draw(rectangulo1);
            // Dibuja un cuadrado en la parte inferior
            Rectangle2D rectangulo2 = new Rectangle2D.Double(x, d.height - alto, alto, alto);
            x += alto;
            g2.draw(rectangulo2);
        }
    }//GEN-LAST:event_rectButtonActionPerformed

    private void ellipseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellipseButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
       
        int numeroElipses = 5;
        Color[] colores = {Color.red, Color.green, Color.blue};
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        for (int i = 0; i < numeroElipses; i++) {
            // Establece el color de la elipse
            g2.setPaint(colores[i % colores.length]);
            double ancho = d.width / (i + 1);
            double alto = d.height / (i + 1);
            double x1 = (d.width - ancho) / 2;
            double y = (d.height - alto) / 2;
            double x2 = (d.width - alto) / 2;
            // Dibuja una elipse
            Ellipse2D elipse1 = new Ellipse2D.Double(x1, y, ancho, alto);
            g2.draw(elipse1);
            // Dibuja un circulo
            Ellipse2D elipse2 = new Ellipse2D.Double(x2, y, alto, alto);
            g2.draw(elipse2);
        }

    }//GEN-LAST:event_ellipseButtonActionPerformed

    private void rectRoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectRoundButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        int numeroRectangulos = 5;
        Color[] colores = {Color.red, Color.green, Color.blue};
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double x = 0;
        for (int i = 0; i < numeroRectangulos; i++) {
            // Establece el color de la rectangulo
            g2.setPaint(colores[i % colores.length]);
            double paso = d.width / numeroRectangulos;
            double alto = paso / (i + 1);
            double aw = paso / 5;
            double ah = alto / 5;
            // Dibuja una rectangulo en parte superior
            RoundRectangle2D rectangulo1 = new RoundRectangle2D.Double(i * paso, 0, paso, alto, aw, ah);
            g2.draw(rectangulo1);
            // Dibuja una cuadradoo en la parte inferior
            RoundRectangle2D rectangulo2 = new RoundRectangle2D.Double(x, d.height - alto, alto, alto, ah, ah);
            x += alto;
            g2.draw(rectangulo2);
        }
    }//GEN-LAST:event_rectRoundButtonActionPerformed

    private void arcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        int numeroArcos = 4;
        Color[] colores = {Color.red, Color.green, Color.blue};
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        for (int i = 0; i < numeroArcos; i++) {
            // Establece el color del arco
            g2.setPaint(colores[i % colores.length]);
            double ancho = d.width / (i + 1);
            double alto = d.height / (i + 1);
            double x1 = (d.width - ancho) / 2;
            double y = (d.height - alto) / 2;
            double x2 = (d.width - alto) / 2;
            // Dibuja un arco elíptico
            Arc2D arco1 = new Arc2D.Double(x1, y, ancho, alto, 90 * i, 45, i % 3);
            g2.draw(arco1);
            // Dibuja un arco circular
            Arc2D arco2 = new Arc2D.Double(x2, y, alto, alto, 90 * i, 45, i % 3);
            g2.draw(arco2);
        }


    }//GEN-LAST:event_arcButtonActionPerformed

    private void pathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathButtonActionPerformed

        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        // Establece el color de la trayectoria
        g2.setPaint(Color.blue);
        // crea la trayectoria
        Path2D trayectoria = new Path2D.Double(Path2D.WIND_EVEN_ODD);
        trayectoria.moveTo(50, 50);
        trayectoria.lineTo(70, 44);
        trayectoria.curveTo(100, 10, 140, 80, 160, 80);
        trayectoria.lineTo(190, 40);
        trayectoria.lineTo(200, 56);
        trayectoria.quadTo(100, 150, 70, 60);
        trayectoria.closePath();
        // Dibuja la trayectoria
        g2.draw(trayectoria);


    }//GEN-LAST:event_pathButtonActionPerformed

    private void opsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        Area area1, area2;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 6;
        double alto = d.height / 4;
        double x = 50;
        double y = 25;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la union de las areas
        area2.add(area1);
        // Rellana la union de las areas
        g2.setPaint(Color.red);
        g2.fill(area2);
        x += 100 + ancho;
        y = 25;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la resta de las areas
        area2.subtract(area1);
        // Rellana la resta de las areas
        g2.setPaint(Color.yellow);
        g2.fill(area2);
        x = 50;
        y = 100 + alto;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la interseccion de las areas
        area2.intersect(area1);
        // Rellena la interseccion de las areas
        g2.setPaint(Color.green);
        g2.fill(area2);
        x += 100 + ancho;
        y = 100 + alto;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la union exclusiva de las areas
        area2.exclusiveOr(area1);
        // Rellena la union exclusiva de las areas
        g2.setPaint(Color.cyan);
        g2.fill(area2);
    }//GEN-LAST:event_opsButtonActionPerformed

    private void fillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 4;
        double alto = d.height / 4;
        double x = 50;
        double y = 25;
        // Rellena una elipse con un color solido
        Ellipse2D elipse = new Ellipse2D.Double(x, y, ancho, alto);
        g2.setPaint(Color.yellow);
        g2.fill(elipse);
        x += 100 + ancho;
        // Crea un gradiente de color
        GradientPaint gp = new GradientPaint((int) x, (int) y, Color.red,
                (int) (x + ancho), (int) (y + alto), Color.blue);
        // Rellena un rectangulo con un gradiente de color
        Rectangle2D rect = new Rectangle2D.Double(x, y, ancho, alto);
        g2.setPaint(gp);
        g2.fill(rect);
        x = 50 + ancho;
        y = 100 + alto;
        // Carga la imagen a ser usada como textura
        BufferedImage bi = null;

        try {
            bi = getImage("fondo.jpg");
        } catch (IOException ex) {
            Logger.getLogger(CanvasFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Crea el rectangulo ancla del tamaño de la imagen
        Rectangle2D tr = new Rectangle2D.Double(0, 0, bi.getWidth(), bi.getHeight());
        // Crea la textura
        TexturePaint tp = new TexturePaint(bi, tr);
        // Rellena el rectangulo con la textura
        RoundRectangle2D rrect = new RoundRectangle2D.Double(x, y, ancho, alto, ancho / 5, alto / 5);
        g2.setPaint(tp);
        g2.fill(rrect);
    }//GEN-LAST:event_fillButtonActionPerformed

    private void contourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contourButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        Area area1, area2;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        // Crea dos contornos
        BasicStroke bs1 = new BasicStroke(3);
        BasicStroke bs2 = new BasicStroke(15);
        double ancho = d.width / 6;
        double alto = d.height / 4;
        double x = 50;
        double y = 25;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Establece el tipo de contorno
        float[] dash1 = {10, 5};
        BasicStroke bs3 = new BasicStroke(1, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_BEVEL, 0, dash1, 0);
        g2.setStroke(bs3);
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la union de las areas
        area2.add(area1);
        // Dibuja la union de las areas
        g2.setStroke(bs1);
        g2.setPaint(Color.red);
        g2.draw(area2);
        x += 100 + ancho;
        y = 25;
        // Obten el area de una figura rectangular
        area1 = new Area(new Rectangle2D.Double(x, y, ancho, alto));
        x += ancho / 2;
        y += alto / 2;
        // Obten el area de una figura eliptica
        area2 = new Area(new Ellipse2D.Double(x, y, ancho, alto));
        // Establece el tipo de contorno
        float[] dash2 = {5, 10, 10, 5};
        BasicStroke bs4 = new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, dash2, 0);
        g2.setStroke(bs4);
        // Dibuja las dos areas
        g2.setPaint(Color.black);
        g2.draw(area1);
        g2.draw(area2);
        // Obten la resta de las areas
        area2.subtract(area1);
        // Dibuja la resta de las areas
        g2.setStroke(bs1);
        g2.setPaint(Color.yellow);
        g2.draw(area2);
        x = 50;
        y = 100 + alto;
        // Crea una figura rectangular
        Rectangle2D rect = new Rectangle2D.Double(x, y, 2 * ancho, alto);
        // Crea un gradiente de color
        GradientPaint gp = new GradientPaint((int) x, (int) y, Color.red,
                (int) (x + 2 * ancho), (int) (y + alto), Color.blue);
        // Establece el tipo de contorno
        g2.setStroke(bs2);
        // Dibuja el rectangulo
        g2.setPaint(gp);
        g2.draw(rect);
        x += 50 + 2 * ancho;
        y = 100 + alto;
        // Crea de una figura eliptica
        Ellipse2D elipse = new Ellipse2D.Double(x, y, 2 * ancho, alto);
        // Carga la imagen a ser usada como textura
        BufferedImage bi;
        try {
            bi = getImage("fondo.jpg");
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(canvasPanel, "Error al cargar imagen");
            return;
        }
        // Crea el rectangulo ancla del tamaño de la imagen
        Rectangle2D tr = new Rectangle2D.Double(0, 0, bi.getWidth(), bi.getHeight());
        TexturePaint tp = new TexturePaint(bi, tr);
        // Establece el tipo de contorno
        g2.setStroke(bs2);
        // Dibuja la elipse
        g2.setPaint(tp);
        g2.draw(elipse);
    }//GEN-LAST:event_contourButtonActionPerformed

    private void translateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 4;
        double alto = d.height / 4;
        double x = 50;
        double y = 25;
        // Establece el tipo de contorno
        BasicStroke bs = new BasicStroke(2);
        g2.setStroke(bs);

        // Establece el color del contorno
        g2.setPaint(Color.blue);
        // Crea una figura rectangular
        Rectangle2D rect = new Rectangle2D.Double(x, y, ancho, alto);
        // Crea de una figura eliptica
        Ellipse2D.Double elipse = new Ellipse2D.Double(x, y, ancho,
                alto);
        // Establece el origen inicial
        g2.translate(10, 10);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Translada el origen
        g2.translate(2 * ancho, 0);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Translada el origen
        g2.translate(0, 2 * alto);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
    }//GEN-LAST:event_translateButtonActionPerformed

    private void rotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 4;
        double alto = d.height / 4;
        // Establece la posición inicial del origen
        g2.translate(2 * ancho, 2 * alto);
        // Establece el tipo de contorno
        BasicStroke bs = new BasicStroke(2);
        g2.setStroke(bs);
        // Establece el color del contorno
        g2.setPaint(Color.blue);
        // Crea una figura rectangular
        Rectangle2D.Double rect = new Rectangle2D.Double(-ancho / 2,
                -alto / 2, ancho, alto);
        // Crea de una figura eliptica
        Ellipse2D.Double elipse = new Ellipse2D.Double(-ancho / 2, -alto / 2,
                ancho, alto);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo
        g2.draw(rect);
        g2.draw(elipse);
        // Rota el origen
        g2.rotate(Math.PI / 4);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo
        g2.draw(rect);
        g2.draw(elipse);
        // Rota el origen
        g2.rotate(Math.PI / 4);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);

        // Dibuja el rectangulo
        g2.draw(rect);
        g2.draw(elipse);
    }//GEN-LAST:event_rotateButtonActionPerformed

    private void scaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();

        double ancho = d.width / 4;
        double alto = d.height / 4;
        double x = 50;
        double y = 25;
        // Establece el tipo de contorno
        BasicStroke bs = new BasicStroke(2);
        g2.setStroke(bs);
        // Establece el color del contorno
        g2.setPaint(Color.blue);
        // Crea una figura rectangular
        Rectangle2D.Double rect = new Rectangle2D.Double(x, y, ancho, alto);
        // Crea de una figura eliptica
        Ellipse2D.Double elipse = new Ellipse2D.Double(x, y, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Escala la imagen
        g2.scale(1.5, 1.5);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Escala la imagen
        g2.scale(1.5, 1.5);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
    }//GEN-LAST:event_scaleButtonActionPerformed

    private void shearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shearButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 4;
        double alto = d.height / 4;
        double x = 50;
        double y = 10;
        // Establece el tipo de contorno
        BasicStroke bs = new BasicStroke(2);
        g2.setStroke(bs);
        // Establece el color del contorno

        g2.setPaint(Color.blue);
        // Crea una figura rectangular
        Rectangle2D rect = new Rectangle2D.Double(x, y, ancho, alto);
        // Crea de una figura eliptica
        Ellipse2D.Double elipse = new Ellipse2D.Double(x, y, ancho,
                alto);
        // Establece el origen inicial
        g2.translate(10, 10);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Translada el origen
        g2.translate(2 * ancho, 0);
        // Deforma horizontalmente
        g2.shear(0.5, 0);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Quita la deformación horizontal
        g2.shear(-0.5, 0);
        // Translada el origen
        g2.translate(-2 * ancho, 2 * alto);
        // Deforma verticalmente
        g2.shear(0, 0.2);
        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
        // Quita la deformación vertical
        g2.shear(0, -0.2);
        // Translada el origen
        g2.translate(2 * ancho, 0);
        // Deforma horizontal y verticalmente
        g2.shear(0.5, 0.2);

        // Dibuja los ejes coordenados
        dibujaEjes(g2, ancho, alto);
        // Dibuja el rectangulo y la elipse
        g2.draw(rect);
        g2.draw(elipse);
    }//GEN-LAST:event_shearButtonActionPerformed

    private void clipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clipButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        Area area1, area2;
        // Obtiene el tamaño del panel
        Dimension d = canvasPanel.getSize();
        double ancho = d.width / 3;
        double alto = d.height / 3;
        double x = 50;
        double y = 25;
        // Carga la imagen a ser usada como textura
        BufferedImage bi;
        try {
            bi = getImage("fondo.jpg");
        } catch (IOException ioe) {

            JOptionPane.showMessageDialog(canvasPanel,
                    "Error al cargar imagen");
            return;
        }
        // Crea el rectangulo ancla del tamaño de la imagen
        Rectangle2D tr = new Rectangle2D.Double(0, 0, bi.getWidth(),
                bi.getHeight());
        TexturePaint tp = new TexturePaint(bi, tr);
        // establece el tipo de relleno
        g2.setPaint(tp);
        // Crea una figura rectangular
        Rectangle2D rect1 = new Rectangle2D.Double(x, y, ancho, alto);
        // Dibuja el rectangulo
        g2.fill(rect1);
        x += 100 + ancho;
        // Crea una figura rectangular
        Rectangle2D rect2 = new Rectangle2D.Double(x, y, ancho, alto);
        // Crea la figura de recorte
        Ellipse2D elipse1 = new Ellipse2D.Double(x, y, ancho, alto);
        g2.clip(elipse1);
        // Dibuja el rectangulo
        g2.fill(rect2);
        // Elimina el recorte
        g2.setClip(null);
        x = 50;
        y = 50 + alto;
        // Crea una figura rectangular
        Rectangle2D rect3 = new Rectangle2D.Double(x, y, ancho, alto);
        // Crea la figura de recorte
        Ellipse2D elipse2 = new Ellipse2D.Double(x, y, ancho, alto);
        g2.clip(elipse2);
        // Crea otra figura de recorte
        Rectangle2D rect4 = new Rectangle2D.Double(x, y, alto, alto);
        g2.clip(rect4);
        // Dibuja el rectangulo
        g2.fill(rect3);
    }//GEN-LAST:event_clipButtonActionPerformed

    private void textButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
          
        // Crea un tipo de fuente
        Font font = new Font("Serif", Font.PLAIN, 96);
        // Establece el tipo de fuente
        g2.setFont(font);
        // Dibuja una cadena de texto
        g2.drawString("Hola mundo", 20, 100);
        // Establece la sugerencia de usar suavizamiento de orillas
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        // Dibuja una cadena de texto
        g2.drawString("Hola mundo", 20, 200);
    }//GEN-LAST:event_textButtonActionPerformed

    private void rotateTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateTextButtonActionPerformed
        Graphics g = canvasPanel.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        float x, y;
        // Crea un tipo de fuente
        Font font = new Font("Serif", Font.PLAIN, 48);
        // Establece el tipo de fuente

        g2.setFont(font);
        // Establece la sugerencia de usar suavizamiento de orillas
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        // Establece el origen de coordenadas
        g2.translate(80, 250);
        // Dibuja una cadena de texto
        g2.drawString("Hola mundo", 0, 0);
        // Gira el sistema coordenado 45 grados
        g2.rotate(-Math.PI / 4);
        // Dibuja una cadena de texto
        g2.drawString("Hola mundo", 0, 0);
        // Gira el sistema coordenado otros 45 grados
        g2.rotate(-Math.PI / 4);
        // Dibuja una cadena de texto
        g2.drawString("Hola mundo", 0, 0);
    }//GEN-LAST:event_rotateTextButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        canvasPanel.repaint();
    }//GEN-LAST:event_clrButtonActionPerformed

    private void canvasPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        System.out.println(x + " " + y);

        double diffx = Math.abs(aoi.getCentreX() - x);
        double diffy = Math.abs(aoi.getCentreY() - y);
        double distance = Math.sqrt(diffx * diffx + diffy * diffy); 
        // if (Math.abs(x - aoi.getCentreX()) < aoi.getRadius() && Math.abs(y - aoi.getCentreY()) < aoi.getRadius()){
        // if (distance < aoi.getRadius()) {  // alternative: use Point2D.distance(....)
        if (aoi.getEllipse().contains(x, y)) {
            if (aoi.getColor() == Color.RED) {
                aoi.setColor(Color.GREEN);
            } else {
                aoi.setColor(Color.RED);
            }
            aoi.paint();

        }


    }//GEN-LAST:event_canvasPanelMouseClicked

    private void aoiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoiButtonActionPerformed

        aoi.paint();


    }//GEN-LAST:event_aoiButtonActionPerformed

    /**
     * Este método estático dibuja unos ejes coordenados en el contexto g2
     *
     * @param g2 Contexto de Graphics2D en el que se dibujan los ejes
     * @param ancho Longitud del eje X
     * @param alto Longitud del eje Y
     */
    public static void dibujaEjes(Graphics2D g2, double ancho,
            double alto) {
        BasicStroke bs1 = new BasicStroke(2, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_BEVEL, 0,
                new float[]{5, 5}, 0);
        // Crea los ejes coordenados
        Line2D ejeX = new Line2D.Double(-10, 0, ancho, 0);
        Line2D ejeY = new Line2D.Double(0, -10, 0, alto);

        // Guarda los valores de Paint y Stroke actuales
        Paint paint = g2.getPaint();
        Stroke stroke = g2.getStroke();
        // Establece los nuevos valores de Paint y Stroke
        g2.setStroke(bs1);
        g2.setPaint(Color.black);
        // Dibuja los ejes coordenados
        g2.draw(ejeX);
        g2.draw(ejeY);
        // Reestablece los valores de Paint y Stroke originales
        g2.setStroke(stroke);
        g2.setPaint(paint);
    }

    /**
     * Lee la imagen a ser usada como textura de un archivo
     *
     * @param filename Nombre del archivo con la imagen
     * @return Imagen
     * @throws IOException si hay un problema al cargar la imagen
     * @throws ImageFormatException Si hay un problema al formatear la imagen
     */
    public BufferedImage getImage(String filename) throws IOException {
        
        // Lee la imagen JPEG del archivo.
        BufferedImage bi = ImageIO.read(new File("src/resources/"+filename));

        return bi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanvasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanvasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanvasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanvasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CanvasFrame cf = new CanvasFrame();
                cf.setLocationRelativeTo(null);
                cf.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aoiButton;
    private javax.swing.JButton arcButton;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JButton clipButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton contourButton;
    private javax.swing.JButton cubicButton;
    private javax.swing.JButton ellipseButton;
    private javax.swing.JButton fillButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton linesButton1;
    private javax.swing.JButton opsButton;
    private javax.swing.JButton pathButton;
    private javax.swing.JButton quadButton;
    private javax.swing.JButton rectButton;
    private javax.swing.JButton rectRoundButton;
    private javax.swing.JButton rotateButton;
    private javax.swing.JButton rotateTextButton;
    private javax.swing.JButton scaleButton;
    private javax.swing.JButton shearButton;
    private javax.swing.JButton textButton;
    private javax.swing.JButton translateButton;
    // End of variables declaration//GEN-END:variables
}
